services:
  backend:
    image: vuduy111/mern-backend:1.0
    network_mode: host
    env_file:
      - .env

  frontend:
    image: vuduy111/mern-frontend:2.0
    ports:
      - "4173:4173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
